//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate_Cover_Letter
    {
        public int Cover_Letter_id { get; set; }
        public Nullable<int> Candidate_CV_Id { get; set; }
        public Nullable<int> Candidate_id { get; set; }
        public string Cover_Letter_file { get; set; }
    }
}
