//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public int Candidate_id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email_Id { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> Mobile_No { get; set; }
        public string Functional_Area { get; set; }
        public Nullable<int> Current_Sallery { get; set; }
        public string Education_level { get; set; }
        public string Experience_Level { get; set; }
        public string Desired_Salary_from { get; set; }
        public string Desired_Salary_to { get; set; }
        public string Current_Carrier_Level { get; set; }
        public string Religion { get; set; }
        public string Birht_Place { get; set; }
        public string Marital_Status { get; set; }
        public string Father_Namer { get; set; }
        public string Postal_Addres { get; set; }
        public string Permanent_Addres { get; set; }
        public string CNIC { get; set; }
        public string Driving_Licience { get; set; }
    }
}
