//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate_Courses
    {
        public int Course_id { get; set; }
        public Nullable<int> Candidate_id { get; set; }
        public string Course_Type { get; set; }
        public string Course_Start_Date { get; set; }
        public string Course_End_Date { get; set; }
        public string Institute { get; set; }
    }
}
