//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate_desired_city
    {
        public int Desired_city_id { get; set; }
        public Nullable<int> Candidate_id { get; set; }
        public string Desired_city_name { get; set; }
    }
}
