//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_jobs_realted_skills
    {
        public int Company_jobs_related_skil_id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public string Skill_title { get; set; }
        public string skills_discription { get; set; }
        public Nullable<int> Company_Vacancy_id { get; set; }
        public Nullable<int> Advertisement_id { get; set; }
    }
}
