//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_ShortListed
    {
        public int ShortListes_Id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public Nullable<int> Candidate_id { get; set; }
        public Nullable<int> Company_Vacancy_id { get; set; }
        public Nullable<int> Advertisement_id { get; set; }
        public string Shorlisted_Date { get; set; }
    }
}
