//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Profile
    {
        public int Company_id { get; set; }
        public string Company_Name { get; set; }
        public string Company_Since { get; set; }
        public string Company_Website { get; set; }
        public string Company_Employess { get; set; }
        public string Company_Description { get; set; }
    }
}
