//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_SharedAdd_Media
    {
        public int Media_Shared_id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public string Media { get; set; }
        public string Link { get; set; }
        public string Shared_Date { get; set; }
    }
}
