//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobsPortalEntities : DbContext
    {
        public JobsPortalEntities()
            : base("name=JobsPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Candidate> Candidates { get; set; }
        public DbSet<Candidate_Achievements> Candidate_Achievements { get; set; }
        public DbSet<Candidate_Courses> Candidate_Courses { get; set; }
        public DbSet<Candidate_Cover_Letter> Candidate_Cover_Letter { get; set; }
        public DbSet<Candidate_CV> Candidate_CV { get; set; }
        public DbSet<Candidate_desired_city> Candidate_desired_city { get; set; }
        public DbSet<Candidate_Education> Candidate_Education { get; set; }
        public DbSet<Candidate_Education_Major_Subjects> Candidate_Education_Major_Subjects { get; set; }
        public DbSet<Candidate_Experience> Candidate_Experience { get; set; }
        public DbSet<Candidate_Feedback> Candidate_Feedback { get; set; }
        public DbSet<Candidate_Jobs_Appllied> Candidate_Jobs_Appllied { get; set; }
        public DbSet<Candidate_Jobs_Types_Looking> Candidate_Jobs_Types_Looking { get; set; }
        public DbSet<Candidate_Languages> Candidate_Languages { get; set; }
        public DbSet<Candidate_Professional_Skills> Candidate_Professional_Skills { get; set; }
        public DbSet<Candidate_Projects> Candidate_Projects { get; set; }
        public DbSet<Candidate_Publications> Candidate_Publications { get; set; }
        public DbSet<Candidate_Query> Candidate_Query { get; set; }
        public DbSet<Candidate_Saved_Jobs> Candidate_Saved_Jobs { get; set; }
        public DbSet<Candidate_Specilization> Candidate_Specilization { get; set; }
        public DbSet<Company_Admin> Company_Admin { get; set; }
        public DbSet<Company_Advertisments> Company_Advertisments { get; set; }
        public DbSet<Company_Education_Required> Company_Education_Required { get; set; }
        public DbSet<Company_Files> Company_Files { get; set; }
        public DbSet<Company_FunctionalArea> Company_FunctionalArea { get; set; }
        public DbSet<Company_Industry> Company_Industry { get; set; }
        public DbSet<Company_Interview> Company_Interview { get; set; }
        public DbSet<Company_jobs_realted_skills> Company_jobs_realted_skills { get; set; }
        public DbSet<Company_Locations> Company_Locations { get; set; }
        public DbSet<Company_phone_No> Company_phone_No { get; set; }
        public DbSet<Company_Profile> Company_Profile { get; set; }
        public DbSet<Company_Question_Choices> Company_Question_Choices { get; set; }
        public DbSet<Company_Selected_Recieved_Applications> Company_Selected_Recieved_Applications { get; set; }
        public DbSet<Company_Services> Company_Services { get; set; }
        public DbSet<Company_SharedAdd_Media> Company_SharedAdd_Media { get; set; }
        public DbSet<Company_ShortListed> Company_ShortListed { get; set; }
        public DbSet<Company_Tests> Company_Tests { get; set; }
        public DbSet<Company_Vacancies> Company_Vacancies { get; set; }
        public DbSet<Company_Vacancy_Locations> Company_Vacancy_Locations { get; set; }
        public DbSet<Company_Vacancy_Questions> Company_Vacancy_Questions { get; set; }
        public DbSet<Compnay_FinalShortListed> Compnay_FinalShortListed { get; set; }
        public DbSet<Country> Countries { get; set; }
    }
}
