//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate_Education
    {
        public int Education_Id { get; set; }
        public Nullable<int> Candidate_id { get; set; }
        public string Degree_Title { get; set; }
        public string Degree_Type { get; set; }
        public string Degree_Level { get; set; }
        public string Institute { get; set; }
        public string Result_Type { get; set; }
        public string Start_Date { get; set; }
        public string Completion_Date { get; set; }
    }
}
