//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate_Languages
    {
        public int Language_id { get; set; }
        public Nullable<int> Candidate_id { get; set; }
        public string Language_Name { get; set; }
        public string Proficiency { get; set; }
        public string Description { get; set; }
    }
}
