//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate_Experience
    {
        public int Experience_id { get; set; }
        public Nullable<int> Candidate_id { get; set; }
        public string title { get; set; }
        public string Company { get; set; }
        public string Locaton { get; set; }
        public string Start_From_date { get; set; }
        public string End_Date { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string Designation { get; set; }
        public string Salary { get; set; }
    }
}
