//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate_Projects
    {
        public int Project_id { get; set; }
        public Nullable<int> Candidate_id { get; set; }
        public string Project_Title { get; set; }
        public string Description { get; set; }
        public string Project_Url { get; set; }
        public string Status { get; set; }
        public string Assocication_with { get; set; }
        public string Project_Start_date { get; set; }
        public string Project_End_Date { get; set; }
    }
}
