//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate_Specilization
    {
        public int Specilization_id { get; set; }
        public Nullable<int> Candidate_id { get; set; }
        public string Specilization_title { get; set; }
        public string Specilization_Description { get; set; }
    }
}
