//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate_Publications
    {
        public int Publication_id { get; set; }
        public Nullable<int> Candidate_id { get; set; }
        public string Publication_title { get; set; }
        public string Author { get; set; }
        public string Publish_date { get; set; }
        public string Desciption { get; set; }
    }
}
