//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Advertisments
    {
        public int Advertisement_id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public string Advertisement_title { get; set; }
        public string AD_Date_Submission { get; set; }
        public string Ad_Expiry_Date { get; set; }
        public string Status { get; set; }
        public string Is_Allowed { get; set; }
    }
}
