//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Admin
    {
        public int Company_Admin_id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public string Admin_Name { get; set; }
        public string Admin_Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Phone_No { get; set; }
        public Nullable<int> Vouchar_No { get; set; }
        public string Admin_Desingnation { get; set; }
        public string Status { get; set; }
    }
}
