//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Vacancies
    {
        public int Company_Vacancy_id { get; set; }
        public Nullable<int> Advertisement_id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public string Discription { get; set; }
        public string Vacancy_title { get; set; }
        public string Career_level { get; set; }
        public Nullable<int> Vacancy_No_of_Postions { get; set; }
        public Nullable<int> Salary_Range_from { get; set; }
        public Nullable<int> Salary_Range_to { get; set; }
        public string Functional_Area { get; set; }
    }
}
