//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Services
    {
        public int Company_Service_id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public string Service_Type { get; set; }
        public string Service_Discritpion { get; set; }
    }
}
